name: Validate and autofix
on:
  push:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: actions/checkout
        uses: actions/checkout@v1.2.0
      - name: actions/setup-node
        uses: actions/setup-node@v1.3.0
        with:
          node-version: "12.13.1"
      - name: npm install
        uses: jaid/action-npm-install@master
      - name: Jest
        uses: jaid/action-jest@master
      - name: Uptodater
        uses: jaid/action-uptodater@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fix: "true"
          approve: "true"